# ¿Por qué enseño?

Cuando comencé a ser voluntario en la Universidad de Toronto, algunos de mis estudiantes me preguntaron por qué iba a enseñar de forma gratuita. Esta fue mi respuesta:

>Cuando tenía tu edad, pensaba que las universidades existían para enseñar a la gente a aprender. Más tarde, en la escuela de posgrado, pensé que las universidades se dedicaban a investigar y crear nuevos conocimientos. Sin embargo, ahora que tengo más de cuarenta años, me he dado cuenta de que lo que realmente le estamos enseñando es cómo dominar el mundo, porque tendrá que decidir si quiere o no.
>
>Mis padres tienen setenta años. Ya no corren el mundo; Son las personas de mi edad las que aprueban leyes y toman decisiones de vida o muerte en los hospitales. Tan aterrador como es, somos los adultos.
>
>Dentro de veinte años, nos dirigiremos a la jubilación y usted estará a cargo. Puede parecer mucho tiempo cuando tienes diecinueve años, pero toma tres respiraciones y desaparecerá. Es por eso que le damos problemas cuyas respuestas no se pueden analizar a partir de las notas del año pasado. Es por eso que lo ponemos en situaciones en las que tiene que descubrir qué debe hacerse en este momento, qué puede dejar para más adelante y qué puede simplemente ignorar. Es porque si no aprende cómo hacer estas cosas ahora, no estará listo para hacerlo cuando sea necesario.

Todo era cierto, pero no era toda la historia. No quiero que la gente haga del mundo un lugar mejor para poder retirarme cómodamente. Quiero que lo hagan porque es la mayor aventura de nuestro tiempo. Hace ciento cincuenta años, la mayoría de las sociedades practicaban la esclavitud. Hace cien años, mi abuela no era legalmente una persona en Canadá. En el año en que nací, la mayoría de las personas del mundo sufrieron bajo un gobierno totalitario, y los jueces todavía ordenaban la terapia de electrochoque para "curar" a los homosexuales. Todavía hay mucho mal con el mundo, pero mira cuántas opciones más tenemos que nuestros abuelos. Mira cuántas cosas más podemos saber, ser y disfrutar, porque finalmente nos estamos tomando en serio la Regla de Oro.

Hoy soy menos optimista que antes. El cambio climático, la extinción masiva, la vigilancia del capitalismo, la desigualdad en una escala que no hemos visto en un siglo, el resurgimiento del nacionalismo racista: mi generación lo ha visto todo y se encogió de hombros. El proyecto de ley para nuestra cobardía, letargo y avaricia no se pagará hasta que mi hija crezca, pero llegará, y para el momento en que lo haga, no habrá soluciones fáciles para estos problemas (y posiblemente ninguna solución).

Por eso enseño hoy: estoy enojado. Estoy enojado porque tu sexo y tu color y la riqueza y las conexiones de tus padres no deberían contar más que cuán inteligente, honesto o trabajador eres. Estoy enojado porque convertimos Internet en un pozo negro. Estoy enojado porque los nazis están en marcha una vez más y los multimillonarios juegan con cohetes mientras el planeta se derrite. Estoy enojado, así que enseño, porque el mundo solo mejora cuando enseñamos a las personas cómo mejorarlo.

En su ensayo de 1947 "Por qué escribo", George Orwell escribió:

>En una época pacífica, podría haber escrito libros ornamentados o meramente descriptivos, y podría haber permanecido casi inconsciente de mis lealtades políticas. De hecho, me he visto obligado a convertirme en una especie de panfleto ... Cada línea de trabajo serio que he escrito desde 1936 se ha escrito, directa o indirectamente, contra el totalitarismo ... Me parece absurdo, en un período como el nuestro, piensa que uno puede evitar escribir sobre tales temas. Todos escriben de ellos de una manera u otra. Es simplemente una cuestión de qué lado se toma.

Reemplace "escritura" con "enseñanza" y tendrá la razón por la que hago lo que hago.

Gracias por leer. Espero que podamos enseñar juntos algún día. Hasta entonces:

Comience donde está.
Usa lo que tienes.
Ayuda a quien puedas.